In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)
print(a.type())
print(a.shape)
print(a)

torch.FloatTensor
torch.Size([3, 4, 5])
tensor([[[ 0.5797,  0.1073, -0.3378,  1.4138, -1.2229],
         [ 0.4761, -0.8020,  2.1810, -1.0840, -0.5052],
         [-0.0233,  0.5113, -1.1968,  1.3876, -1.0971],
         [ 0.1819, -1.3784, -0.5860, -0.9562, -0.7464]],

        [[-0.3921,  0.8097,  1.4839,  0.8408, -0.8462],
         [-0.7081, -0.7716, -0.1086, -0.7685,  1.3503],
         [ 0.0158,  0.4693, -0.0172,  0.1318,  0.7730],
         [-0.2819,  0.9436, -0.0231,  2.7995, -0.5399]],

        [[ 0.3913, -1.1509, -1.5727, -1.5423,  0.0487],
         [ 0.0650,  0.3755,  2.5418,  0.5924,  0.1639],
         [ 1.1971,  0.9356,  0.3923, -0.7534, -1.0425],
         [-1.2594, -0.7186, -1.3931, -0.6544, -0.9550]]])


In [3]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)
print(a.shape)
print(a)

torch.Size([6, 10])
tensor([[ 0.5797,  0.1073, -0.3378,  1.4138, -1.2229,  0.4761, -0.8020,  2.1810,
         -1.0840, -0.5052],
        [-0.0233,  0.5113, -1.1968,  1.3876, -1.0971,  0.1819, -1.3784, -0.5860,
         -0.9562, -0.7464],
        [-0.3921,  0.8097,  1.4839,  0.8408, -0.8462, -0.7081, -0.7716, -0.1086,
         -0.7685,  1.3503],
        [ 0.0158,  0.4693, -0.0172,  0.1318,  0.7730, -0.2819,  0.9436, -0.0231,
          2.7995, -0.5399],
        [ 0.3913, -1.1509, -1.5727, -1.5423,  0.0487,  0.0650,  0.3755,  2.5418,
          0.5924,  0.1639],
        [ 1.1971,  0.9356,  0.3923, -0.7534, -1.0425, -1.2594, -0.7186, -1.3931,
         -0.6544, -0.9550]])


In [5]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(10, size=(10,)).int()
print(b.type())
print(b)

torch.IntTensor
tensor([8, 1, 1, 1, 1, 2, 6, 1, 3, 3], dtype=torch.int32)


In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
c = a * b
print(c.type())
print(c.shape)
print(c)

torch.FloatTensor
torch.Size([6, 10])
tensor([[ 4.6377,  0.1073, -0.3378,  1.4138, -1.2229,  0.9521, -4.8122,  2.1810,
         -3.2520, -1.5155],
        [-0.1861,  0.5113, -1.1968,  1.3876, -1.0971,  0.3639, -8.2701, -0.5860,
         -2.8687, -2.2391],
        [-3.1370,  0.8097,  1.4839,  0.8408, -0.8462, -1.4162, -4.6295, -0.1086,
         -2.3054,  4.0508],
        [ 0.1266,  0.4693, -0.0172,  0.1318,  0.7730, -0.5638,  5.6618, -0.0231,
          8.3985, -1.6198],
        [ 3.1301, -1.1509, -1.5727, -1.5423,  0.0487,  0.1299,  2.2531,  2.5418,
          1.7771,  0.4918],
        [ 9.5772,  0.9356,  0.3923, -0.7534, -1.0425, -2.5187, -4.3116, -1.3931,
         -1.9633, -2.8651]])


In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
cct = torch.matmul(c, c.T)
print(cct.type())
print(cct.shape)
print(cct)

torch.FloatTensor
torch.Size([6, 6])
tensor([[ 66.8211,  54.4878,   9.3115, -52.8055,   0.9849,  70.6324],
        [ 54.4878,  86.9711,  36.6950, -67.9094, -27.7571,  45.9303],
        [  9.3115,  36.6950,  59.2951, -51.9197, -27.4182, -11.8554],
        [-52.8055, -67.9094, -51.9197, 106.3837,  26.4705, -34.0673],
        [  0.9849, -27.7571, -27.4182,  26.4705,  30.9307,  10.9141],
        [ 70.6324,  45.9303, -11.8554, -34.0673,  10.9141, 133.3438]])


In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)
y = x**3 + z - 75*t
y.backward()
x.grad, z.grad, t.grad

(tensor(3.), tensor(1.), tensor(-75.))

In [9]:
# 8. Создайте единичный тензор размера 5x6
d = torch.ones(5, 6)
print(d.type())
print(d.shape)
print(d)

torch.FloatTensor
torch.Size([5, 6])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [10]:
# 9. Переведите его в формат numpy
d = d.numpy()
print (type(d))
print (d.shape)
print (d)

<class 'numpy.ndarray'>
(5, 6)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
